apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nidsdemo
  name: nidsdemo
  namespace: dhruv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nidsdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nidsdemo
    spec:
      containers:
      - image: nginx
        name: nidsdemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-nids-service
  namespace: dhruv
  labels:
    app: lb-nids-service
spec:
  type: Loadbalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: nidsdemo
